### ISSUE TITLE
Improve 'customize button' set up

### ISSUE THREAD

**Issue by hanseykat** [csytan/cozycal-roadmap#59]

**Comment by hanseykat** [comment]
- [ ] Position section indicating "Bottom left" and "Bottom right" should go directly below "Floating button demo" 
- [ ] For "Floating button demo" -> "Get Embed Code" -> 
"Note: If you use the **WordPress Plugin** this code has already been installed for you." should not be linked to ZenDesk, suggest to remove the link 
- [ ] "Simple button demo" -> "Get Embed Code" --> Remove the "Note" entirely as it is not already installed for WP users

**Comment by csytan** [comment]
Tackling this in #31 and #63
