### ISSUE TITLE
Add explanation and example for "Scheduling settings" -> "Availabilities"

### ISSUE THREAD

**Issue by hanseykat** [csytan/cozycal-roadmap#74]
![image](https://user-images.githubusercontent.com/16357/29543107-a4687e6c-8693-11e7-81e3-47866defab49.png)

**Comment by hanseykat** [comment]
- [ ] Minimum notice (earliest scheduling availability) 

"?: A minimum notice of two weeks means that the earliest possible booking would be two weeks from today. 

For example, if today is January 1st and you set the minimum notice to be a week from today. Then on your calendar, your earliest availability for event scheduling would be shown on January 7th."

- [ ] Maximum notice (Events can be scheduled: 

e.g. 60 days from current date 
"?: A maximum notice of 1 week means that events can no longer be scheduled after 2 weeks  from today. 

For example, if today is January 1st and you set the maximum notice to be 1 week. Then on your calendar, no availability would be shown after Jan 7th."

**Comment by csytan** [comment]
After offline discussion with @hanseykat here are the new labels:
![image](https://user-images.githubusercontent.com/16357/30144877-c83b363e-9342-11e7-8983-5ad862d322be.png)
